### ISSUE TITLE
Support Multiple Request Methods in Endpoint Implementation for Plugin Development

### ISSUE THREAD

**Issue by w2534073922** [langgenius/dify-plugin-sdks#156]
How to implement an endpoint that supports multiple request methods (e.g., GET/POST) for the same interface? 
The current case in the plugin development documentation only allows declaring a single method:
```
path: "/neko"
method: "GET"
extra:
  python:
    source: "endpoints/test_plugin.py"
```

My requirement is to enable a third-party robot to send messages to an AI agent, but the robot's callback URL must support multiple request methods. This requires modifying the endpoint configuration to handle different HTTP methods without being limited to the single-method declaration in the existing documentation.
